### ISSUE TITLE
[Certificate Microservice] As a developer of the app and web I want a microservice for handling certificates

### ISSUE THREAD

**Issue by Jatewo** [Educado-App/educado-certificate-service#2]
- [x] The student certificate should contain:
    - Course name
    - Course creator
    - Estimated course duration
    - Name of student
    - Date of completion
- [x] The student certificate uses static data
- [x] The creator certificate should contain:
    - Course name
    - Course creator
    - Estimated course duration
    - Number of subscribers to the course
    - Average rating of course
- [x] The creator certificate uses dynamic data (points to user and course)

**Comment by MortenMunk** [comment]
- [ ]
